# Generated by Django 3.2.1 on 2021-05-12 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vlog',
            old_name='body',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='vlog',
            old_name='title',
            new_name='titlee',
        ),
    ]
